TILE_EMPTY = 0
TILE_UNKNOWN = 1
TILE_ABSENT = 2
TILE_PRESENT = 3
TILE_CORRECT = 4

COLOR_MAP = {
    TILE_EMPTY: "#d3d6da",
    TILE_UNKNOWN: "#878a8c",
    TILE_ABSENT: "#787c7e",
    TILE_PRESENT: "#c9b458",
    TILE_CORRECT: "#6aaa64",
}

QUERTY_LAYOUT = ["QWERTYUIOP", "ASDFGHJKL", "\rZXCVBNM\b"]
